apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: cokco
  name: cokco
spec:
  containers:
  - image: tkdgur1756/cok-co:0.1
    name: cokco
    ports:
    - containerPort: 3000
      protocol: TCP
